"""Second

Revision ID: 05283a58bd94
Revises: 4a6181201772
Create Date: 2018-09-19 12:19:35.070904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05283a58bd94'
down_revision = '4a6181201772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
